site_name: NAISS Intro week 
repo_url: https://github.com/NAISS-Training/NAISS-intro-week
edit_uri: blob/main/docs/

site_description: Material for the NAISS intro week
site_dir: site.build

theme:
  name: readthedocs
  locale: en
  logo: images/logo.png
    #  logo: images/naiss_logo_white.png
    #  static_templates:
    #- sitemap.html
  include_sidebar: true
  font:
    code: Robot Mono
  features:
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
  tabs: true
  language: en

extra_css:
  - css/extra.css
    #extra_javascript:
    #  - js/popper.min.js
    #  - js/tippy-bundle.umd.js
    #  - js/clipboard.js

nav:
  - Home: index.md
  - Introduction: intro.md
  - Day 1: 
    - Linux Command Line 101: LCL101.md
    - connecting.md
  - Day 2: 
    - Selecting software modules: modules.md
    - Running jobs on clusters: slurm.md  
  - Day 3: 
    - LCL201.md
  - Day 4: 
    - Running AI/ML workloads on NAISS systems: AIML.md
  - Day 5: 
    - sensitive.md 

plugins:
  - search
  - external-markdown
  - mkdocstrings
  - markdown-exec
  - open-in-new-tab

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - smarty
  - pymdownx.details
  - pymdownx.superfences
  - codehilite
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      separator: "__"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
